# Generated by Django 5.1.6 on 2025-11-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='has_baby_bed',
            field=models.BooleanField(default=True, verbose_name='Детская кроватка'),
        ),
    ]
